services:
    db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: "1571438"
      ports:
       - "3306:3306"
    phpmyadmin:
      image: phpmyadmin
      environment:
        PMA_ARBITRARY: 1
      ports:
        - "8080:80"